# Generated by Django 3.0.5 on 2020-05-02 21:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile',
            field=models.ImageField(default='upload/default.png', upload_to=user.models.user_image_path),
        ),
    ]
