# Generated by Django 3.0.5 on 2020-05-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_storeuseranswer'),
        ('user', '0005_auto_20200507_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='challenges',
            field=models.ManyToManyField(to='challenge.ChallengeModel'),
        ),
    ]
