# Generated by Django 3.0.5 on 2020-05-17 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usermodel_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile',
        ),
    ]
