# Generated by Django 3.0.5 on 2020-05-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
